package simpledb.execution;

import simpledb.transaction.TransactionAbortedException;
import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate p;
    private OpIterator child1;
    private OpIterator child2;
    private Tuple tuple1;
    private Tuple tuple2;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return this.p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return this.child1.getTupleDesc().getFieldName(this.p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return this.child2.getTupleDesc().getFieldName(this.p.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        TupleDesc td = TupleDesc.merge(this.child1.getTupleDesc(), this.child2.getTupleDesc());
        return td;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        super.open(); // To invoke the initialisation methods or clean-up logic of Operator.class
        this.child1.open();
        this.child2.open();
    }

    public void close() {
        // some code goes here
        super.close(); // To invoke the initialisation methods or clean-up logic of Operator.class
        this.child1.close();
        this.child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        this.child1.rewind();
        this.child2.rewind();
        this.tuple1 = null;
        this.tuple2 = null;
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        while (true) {
            // Fetch next tuple from child1 if tuple1 is null or child1 has more tuples
            if (this.tuple1 == null && this.child1.hasNext()) {
                this.tuple1 = this.child1.next();
            }
            
            // If child1 has no more tuples, return null
            if (this.tuple1 == null) {
                return null;
            }
            
            // Loop through child2 tuples to find a match
            while (this.child2.hasNext()) {
                // Fetch next tuple from child2
                this.tuple2 = this.child2.next();
                
                // Check if current pair of tuples satisfies the join predicate
                if (p.filter(this.tuple1, this.tuple2)) {
                    // Create a new tuple with fields from tuple1 and tuple2
                    Tuple mergedTuple = new Tuple(getTupleDesc());
                    int td1n = this.tuple1.getTupleDesc().numFields();
                    for (int i = 0; i < td1n; i++)
                        mergedTuple.setField(i, this.tuple1.getField(i));
                    int td2n = this.tuple2.getTupleDesc().numFields();
                    for (int i = 0; i < td2n; i++)
                        mergedTuple.setField(td1n + i, this.tuple2.getField(i));
                    return mergedTuple;
                }
            }
            
            // If child2 has no more tuples, reset child2 and move to the next tuple from child1
            this.child2.rewind();
            this.tuple1 = null;
        }
    }     
    
    @Override
    public OpIterator[] getChildren() {
        // some code goes here
        return new OpIterator[]{this.child1, this.child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // some code goes here
        this.child1 = children[0];
        this.child2 = children[1];
    }
}
